version: '3.8'

services:
  dummy-logger-server:
    build: .
    container_name: dummy-logger-go-server
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    volumes:
      # Optional: Mount logs directory if you want to persist logs
      # - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - dummy-logger-network

networks:
  dummy-logger-network:
    driver: bridge
